---
title: "Combine experiments for count matrix"
author: Rylee K. Hackley
output: 
  html_document:
    keep_md: true
---

```{r, message=FALSE, collapse=TRUE}
library(tidyverse)
library(magrittr)
library(purrr)
library(DESeq2)
```

#wrangling (combining) counts matrices
data from 2022
```{r, message=FALSE, collapse=TRUE}
# read in featureCounts output for new data
count_mat_new <- read_tsv("000_counts_2022/HCA_featureCounts_2022.txt", skip = 1)
count_mat2022 <- as.matrix(count_mat_new[-c(1:6)]) # remove extra columns
rownames(count_mat2022) <- count_mat_new$Geneid # set rownames

# read in meta
meta2022 <- read_csv("000_counts_2022/000_meta.csv")

# check colnames with metadata rownames
colnames(count_mat2022) <- str_remove(colnames(count_mat2022), "03_aligned_sorted/")
colnames(count_mat2022) <- str_remove(colnames(count_mat2022), "_sorted.bam")
colnames(count_mat2022) == meta2022$sample

counts_col22 <- meta2022
counts_col22 <- as.data.frame(count_mat2022)

# add pyrF column to metadata
counts_col22["HAH_RS10105",] %>%
  t() -> tmp
tmp; as.vector(tmp > 67)
meta2022$pyrF <- as.vector(tmp > 67) #max reads mapping to pyrF locus allowed
```

data from 2021
```{r, message=FALSE, collapse=TRUE}
# read in featureCounts output for 2021 data
count_mat2021 <- read_tsv("000_counts_2021/HCA_featureCounts_2021.txt", skip = 1)
colnames(count_mat2021) <- str_remove(colnames(count_mat2021), "bams/")
colnames(count_mat2021) <- str_remove(colnames(count_mat2021), "_sorted.bam")
counts2021 <- count_mat2021

# read in meta
meta2021 <- read_csv("000_counts_2021/000_meta.csv")

#remove rows from data that are not in metadata (48hr samples)
counts2021 <- dplyr::select(counts2021, c("Geneid", meta2021$sample))

# check colnames with metadata rownames
colnames(counts2021) %in% meta2021$sample

# add pyrF column
counts2021[counts2021$Geneid == "HAH_RS10105",][-1] %>%
  t() -> tmp
tmp; as.vector(tmp > 153)
meta2021$pyrF <- as.vector(tmp > 153) #max reads mapping to pyrF locus allowed
```

combine 2 experiments
```{r, collapse=TRUE}
meta <- rbind(meta2022, meta2021)
counts <- cbind(count_mat2022, counts2021[-1])

# calc total reads per sample
data.frame("total counts" = colSums(as.matrix(counts))) -> cnt_sums
cnt_sums <- rownames_to_column(cnt_sums, "sample_name")

counts <- rownames_to_column(counts, "locus_tag")
```

```{r, collapse=TRUE}
# export combined counts
write_csv(counts, "00_deseq2_input/00_combined_counts.csv")
write_csv(meta, "00_deseq2_input/00_combined_meta.csv")
write_csv(cnt_sums, "00_deseq2_input/00_counts_sums.csv")
```